services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:gitlab-ci-dev	
  COMPOSE_CMD: docker-compose -f docker-compose.yml -f deploy/prod.yml

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export API_IMAGE_TAG=$CONTAINER_TEST_IMAGE

build:
  stage: build
  script:
    - $COMPOSE_CMD pull || true
    - $COMPOSE_CMD build
    - $COMPOSE_CMD push

tests:
  stage: test
  script:
    - $COMPOSE_CMD pull
    - $COMPOSE_CMD run api sh -c './manage.py test_all'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
