# Compose used for production

version: '3.5'

services:

  httpapi:
    image: nginx:1.15-alpine
    container_name: httpapi
    restart: always
    volumes:
      - app_static:/app_static
      - app_sockets:/sockets
      - type: volume
        source: app_deploy_config
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
    ports:
      - "9002:80"
    depends_on:
      - api

  api:
    build:
      context: ${BACKEND_PATH:-.}
      dockerfile: ${BACKEND_PATH:-.}/deploy/Dockerfile
    image: ${API_IMAGE_TAG:-agoradigital/agorapi}
    container_name: agorapi
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-segredo}
    restart: always
    volumes:
      - app_sockets:/sockets
      - app_static:/agora-digital-backend/static
      - app_deploy_config:/nginx_config
    depends_on:
      - db

volumes:
  postgres_data:
  app_sockets:
  app_static:
  app_deploy_config:
